### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by gmacario** [CAgduni/ggg#1]
As of https://github.com/CAgduni/LRTPanelYC/commit/d5abf7777b790e68438559a0358d0905b06f0563 the repository has no LICENSE file.

Please add a LICENSE file which clarifies the ownership and the license of the files that are contained inside this repository, so that future updates and/or Pull Requests will adopt the same license.

I am not a layer but if possible I would suggest to choose the MIT license which is compatible with https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/

**Comment by karthago1** [comment]
I have attached a license file (MIT) without consulting my boss :-). For the moment, we don't care about the type of the license, because there is no secrets to hide. But later, there is the possibility to change it, if you or my boss requests another type of License.
